### ISSUE TITLE
CORE-23: CDP Handler for MCD

### ISSUE THREAD

**Issue by tomedwardsmith** [makerdao/mcd-cdp-handler#6]
This is mainly a smart contract which will wrap the CDP and will allow you to transfer it. 
Also potentially to close it. 
Gonzalo working on a draft. Will share for feedback once done. 
Proposal started with Mariano a few weeks ago. 
Working on docs and solidity prototype.

**Comment by tomedwardsmith** [comment]
@gbalabasquer can we close this one now we have moved to adopt the CDP manager? Where are we tracking work on the CDP manager replacement at the moment?

**Comment by gbalabasquer** [comment]
@tomedwardsmith It is not decided 100% that we will use the cdp-manager instead of this yet. However we can create new issues if we need to do some future work here.
